"""empty message

Revision ID: 747eca61ed3e
Revises: f4d7fdcfdd4c
Create Date: 2025-01-06 00:41:05.290159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747eca61ed3e'
down_revision = 'f4d7fdcfdd4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
